# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
name: "NpmRunBuild"

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.13
      - run: npm ci
      - run: npm run build
        working-directory: ./dist